/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutScanRouteImport } from './routes/_layout/scan'
import { Route as LayoutCheckoutRouteImport } from './routes/_layout/checkout'
import { Route as LayoutSessionSessionIdRouteImport } from './routes/_layout/session.$sessionId'
import { Route as LayoutMenuVendorIdRouteImport } from './routes/_layout/menu.$vendorId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutScanRoute = LayoutScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCheckoutRoute = LayoutCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSessionSessionIdRoute = LayoutSessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMenuVendorIdRoute = LayoutMenuVendorIdRouteImport.update({
  id: '/menu/$vendorId',
  path: '/menu/$vendorId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/scan': typeof LayoutScanRoute
  '/menu/$vendorId': typeof LayoutMenuVendorIdRoute
  '/session/$sessionId': typeof LayoutSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/scan': typeof LayoutScanRoute
  '/menu/$vendorId': typeof LayoutMenuVendorIdRoute
  '/session/$sessionId': typeof LayoutSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/_layout/checkout': typeof LayoutCheckoutRoute
  '/_layout/scan': typeof LayoutScanRoute
  '/_layout/menu/$vendorId': typeof LayoutMenuVendorIdRoute
  '/_layout/session/$sessionId': typeof LayoutSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/scan'
    | '/menu/$vendorId'
    | '/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/scan'
    | '/menu/$vendorId'
    | '/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/auth'
    | '/_layout/checkout'
    | '/_layout/scan'
    | '/_layout/menu/$vendorId'
    | '/_layout/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/scan': {
      id: '/_layout/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof LayoutScanRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/checkout': {
      id: '/_layout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof LayoutCheckoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/session/$sessionId': {
      id: '/_layout/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof LayoutSessionSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/menu/$vendorId': {
      id: '/_layout/menu/$vendorId'
      path: '/menu/$vendorId'
      fullPath: '/menu/$vendorId'
      preLoaderRoute: typeof LayoutMenuVendorIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCheckoutRoute: typeof LayoutCheckoutRoute
  LayoutScanRoute: typeof LayoutScanRoute
  LayoutMenuVendorIdRoute: typeof LayoutMenuVendorIdRoute
  LayoutSessionSessionIdRoute: typeof LayoutSessionSessionIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCheckoutRoute: LayoutCheckoutRoute,
  LayoutScanRoute: LayoutScanRoute,
  LayoutMenuVendorIdRoute: LayoutMenuVendorIdRoute,
  LayoutSessionSessionIdRoute: LayoutSessionSessionIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
